ALTER DATABASE [xendesktop_site]
SET READ_COMMITTED_SNAPSHOT ON
GO  
ALTER DATABASE [xendesktop_monitor]
SET READ_COMMITTED_SNAPSHOT ON
GO  
ALTER DATABASE [xendesktop_config]
SET READ_COMMITTED_SNAPSHOT ON
GO  